package com.example.fit5046assignment.roomDb

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a single task item in the database.
 * This data class defines the schema for the "tasks" table.
 */
@Entity(tableName = "tasks") // Marks this class as a Room database entity, specifying the table name.
data class TaskEntity(
    /**
     * The unique identifier for the task. This is the primary key for the table.
     * It is auto-generated by Room, ensuring each task has a unique ID.
     * Defaults to 0, but Room will assign a new value upon insertion if 0 is provided.
     */
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    /**
     * The name or description of the task.
     * e.g., "Grocery shopping", "Prepare presentation"
     */
    val name: String,

    /**
     * The date and time when the task was created.
     * Stored as a String, typically representing milliseconds since epoch, or a formatted date-time string.
     * This field is intended to be immutable after creation.
     */
    val creationDate: String,

    /**
     * The date by which the task is expected to be completed.
     * Stored as a String, typically in "YYYY-MM-DD" format or a more precise date-time string.
     */
    val dueDate: String,

    /**
     * A boolean flag indicating whether the task is marked as important by the user.
     * Defaults to false (not important).
     */
    val isImportant: Boolean = false,
    val isCompleted: Boolean = false,
    val isOverdue: Boolean = false
)